### ISSUE TITLE
(Summary) Meets Expectations

### ISSUE THREAD

**Issue by CharlesDLandau** [kcarullo/dvp-u3-constellations#1]
## Rubric Score
 
### Criteria 1: Matplotlib and CSV
* _Score Level:_ 4
* _Comment(s):_ Imports properly!
 
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ 4
* _Comment(s):_ Nice use of custom detailing - a simple and easy way to make a more distinctive (and apt) visualization.
 
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ 2
* _Comment(s):_ Plotting did not map to Z-axis, see the issue I posted to you
 
### Overall Score: 10/12
Meets Expectations - Well done! Your 3D plot is *so very close* to correct, but it currently stays flat on the Z-axis and I had to ding you for that. Clearly you have a good idea now of how to take a matplotlib task and put your distinctive mark on it, and that's huge!

**Comment by kcarullo** [comment]
Thank you for your feedback.
