### ISSUE TITLE
(3D Plotting) Very close!

### ISSUE THREAD

**Issue by CharlesDLandau** [kcarullo/dvp-u3-constellations#3]
Your code mostly works, but none of the data is mapped to the z-axis! I rearranged your code to fix it. Pay close attention how each variable assignment is called in the subsequent line
```
# Assign a new figure object to a variable
fig_3d = plt.figure() 
# Assign a new subplot object to a variable
constellation = fig_3d.add_subplot(1,1,1, projection="3d") 
# Call the .scatter plotting method on the subplot object
constellation.scatter(x, y, z,color='orange', marker='*')
# High level (pyplot) methods
plt.title('Orion 3D Constellation')
plt.show()
```
https://github.com/kcarullo/dvp-u3-constellations/blob/98a75e35f68a547091d84316f2e280f05e7d3e1c/Constellations%20Project/Constellations.py#L36-L41

**Comment by kcarullo** [comment]
Now I see it must have been rushing on the last part. Thank you.
